=== Epgor/pwi/lab6/dtd/disks.dtd
<!DOCTYPE disks
[
<!ELEMENT disks (audio_disk|video_disk)+>
<!ATTLIST disks
  xmlns CDATA #FIXED ''>

<!ELEMENT audio_disk (autor,dlugosci_nagrania_min,kraj,gatunek)>
<!ATTLIST audio_disk
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT video_disk (flag,tytul,rok)>
<!ATTLIST video_disk
  xmlns CDATA #FIXED ''
  id CDATA #REQUIRED>

<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor
  xmlns CDATA #FIXED ''>

<!ELEMENT dlugosci_nagrania_min (#PCDATA)>
<!ATTLIST dlugosci_nagrania_min
  xmlns CDATA #FIXED ''>

<!ELEMENT kraj (#PCDATA)>
<!ATTLIST kraj
  xmlns CDATA #FIXED ''>

<!ELEMENT gatunek (#PCDATA)>
<!ATTLIST gatunek
  xmlns CDATA #FIXED ''>

<!ELEMENT flag EMPTY>
<!ATTLIST flag kategoria (dla dzieci | dla doroslych) "dla dzieci">

<!ELEMENT tytul (#PCDATA)>
<!ATTLIST tytul
  xmlns CDATA #FIXED ''>

<!ELEMENT rok (#PCDATA)>
<!ATTLIST rok
  xmlns CDATA #FIXED ''>
]>

=== Epgor/pwi/lab6/dtd/disks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE disks SYSTEM "disks.dtd">

<disks>
	<audio_disk id="001">
		<autor>Jones J.</autor>
		<dlugosci_nagrania_min>1:44</dlugosci_nagrania_min>
		<kraj>USA</kraj>
		<gatunek>Folk</gatunek>
	</audio_disk>
	<video_disk id="002">
		<flag kategoria = "dla dzieci" />
		<tytul>Pan Balwanek</tytul>
		<rok>1992</rok>
	</video_disk>
	<audio_disk id="003">
		<autor>Mini Mike</autor>
		<dlugosci_nagrania_min>1:59</dlugosci_nagrania_min>
		<kraj>USA</kraj>
		<gatunek>RAP</gatunek>
	</audio_disk>
	<video_disk id="004">
		<flag kategoria = "dla doroslych" />
		<tytul>swierszczyk dla opornych</tytul>
		<rok>2010</rok>
	</video_disk>
	<audio_disk id="005">
		<autor>Ras Put In</autor>
		<dlugosci_nagrania_min>6:06</dlugosci_nagrania_min>
		<kraj>ZSRR</kraj>
		<gatunek>Electro</gatunek>
	</audio_disk>
	<video_disk id="006">
		<flag kategoria = "dla dzieci" />
		<tytul>zwirek dla kota</tytul>
		<rok>2020</rok>
	</video_disk>
	<audio_disk id="007">
		<autor>Janusz Korwin Mikke</autor>
		<dlugosci_nagrania_min>59:59</dlugosci_nagrania_min>
		<kraj>Polska</kraj>
		<gatunek>RAP</gatunek>
	</audio_disk>
	<video_disk id="008">
		<flag kategoria = "dla dzieci" />
		<tytul>Jak radzic sobie z rurkowcami</tytul>
		<rok>2010</rok>
	</video_disk>
	<audio_disk id="009">
		<autor>Chuck Norris</autor>
		<dlugosci_nagrania_min>3:44</dlugosci_nagrania_min>
		<kraj>USA</kraj>
		<gatunek>Country</gatunek>
	</audio_disk>
	<video_disk id="010">
		<flag kategoria = "dla dzieci" />
		<tytul>Wszystkie sciezki prowadza na odwyk</tytul>
		<rok>2002</rok>
	</video_disk>
</disks>
